package com.webserviceapac.WebServiceApac.Models;

public enum EnumCodigoTipoLeito {

    Cirurgico,
    Obstetricos,
    Clinicos,
    Cronicos,
    Psiquiatria,
    Pneumologia_Sanitaria_Tisiologia,
    Pediatricos,
    Reabilitacao,
    LeitoDia_Cirurgicos,
    LeitoDia_Aids,
    LeitoDia_FibroseCistica,
    LeitoDia_IntercorrenciaPosTransplante,
    LeitoDia_Geriatria,
    LeitoDia_SaudeMental,
    UnidadeIntermediaria,
    UnidadeIntermediariaNeoNAtal,
    Uti_I,
    UtiAdulto_II,
    UtiAdultoIII,
    UtiInfantil_I,
    UtiInfantil_II,
    UtiInfantil_III,
    UtiNeonatal_I,
    UtiNeonatal_II,
    UtiNeonatal_III,
    Uti_Queimados,
    Acolhimento_Noturno,
    Uti_Coronaria_Uco_tipo_II,
    Uti_Coronaria_Uco_tipo_III,
    SaudeMental_Clinico,
    QueimadoAdulto_Clinico,
    QueimadoPediatrico_Clinico,
    QueimadoAdulto_Cirurgico,
    QueimadoPediatrico_Cirurgico,
    Uci_UnidadedeCuidadosIntermediariosNeonatalConvencional,
    Uci_UnidadedeCuidadosIntermediariosNeonatalCanguru,
    Uci_UnidadedeCuidadosIntermediariosPediatricos,
    Uci_UnidadedeCuidadosIntermediariosAdulto,
}
