package com.webserviceapac.WebServiceApac.Models;

public enum EnumTipoLogradouroUsuario {
    ACESSO,
    ADRO,
    ALAMEDA,
    ALTO,
    ATALHO,
    AVENIDA,
    BELVEDERE,
    BECO,
    BLOCO,
    BOSQUE,
    BOULEVARD,
    BAIXA,
    CAIS,
    CAMINHO,
    CONJUNTO,
    COLÔNIA,
    CORREDOR,
    CAMPO,
   CÓRREGO,
    DESVIO,
    DISTRITO,
    ESCADA,
    ESTRADA,
    ESTAÇÃO,
    ESTÁDIO,
    FAVELA,
    FAZENDA,
    FERROVIA,
    FONTE,
    FEIRA,
    FORTE,
    GALERIA,
    GRANJA,
    ILHA,
    JARDIM,
    LADEIRA,
    LARGO,
    LAGOA,
    LOTEAMENTO,
    MORRO,
    MONTE,
    PARALELA,
    PASSEIO,
    PÁTIO,
    PRAÇA,
    PARADA,
    PRAIA,
    PROLONGAMENTO,
    PARQUE,
    PASSARELA,
    PASSAGEM,
    PONTE,
    QUADRA,
    QUINTA,
    BR_277,
    RUA,
    RAMAL,
    RECANTO,
    RETIRO,
    RETA,
    RODOVIA,
    RETORNO,
    SÍTIO,
    SERVIDÃO,
    SETOR,
    SUBIDA,
    TERMINAL,
    TREVO,
    TRAVESSA,
    VIA,
    VIADUTO,
    VILA,
    VIELA,
    VALE,
    ZIGUE_ZAGUE,
    TRECHO,
    VEREDA,
    ARTÉRIA,
    ELEVADA,
    PORTO,
    BALÃO,
    ÁREA,
    JARDINETE,
    ESPLANADA,
    RÓTULA,
    MARINA,
    DESCIDA,
    CIRCULAR,
    UNIDADE,
    CHÁCARA,
    RAMPA,
    PONTA,
    VIA_DE_PEDESTRE,
    CONDOMÍNIO,
    RESIDENCIAL,
    CANAL,
    BURACO,
   MÓDULO,
    LAGO,
    NÚCLEO,
    AEROPORTO,
    PASSAGEM_SUBTERRANEA,
    COMPLEXO_VIÁRIO,
    PRAÇA_DE_ESPORTES,
    VIA_ELEVADO,
    ROTATÓRIA,
//       1ª TRAVESSA,
//        2ª TRAVESSA,
//        3ª TRAVESSA,
//        4ª TRAVESSA,
//        5ª TRAVESSA,
//        6ª TRAVESSA,
//        7ª TRAVESSA,
//        8ª TRAVESSA,
//        9ª TRAVESSA,
//        10ª TRAVESSA,
//        11ª TRAVESSA,
//        12ª TRAVESSA,
//        13ª TRAVESSA,
//        14ª TRAVESSA,
//        15ª TRAVESSA,
//        16ª TRAVESSA,
//        1º ALTO,
//        2º ALTO,
//        3º ALTO,
//        1º BECO,
//        2º BECO,
//        3º BECO,
//        1ª PARALELA,
//        2ª PARALELA,
//        3ª PARALELA,
//        1ª SUBIDA,
//        2ª SUBIDA,
//        3ª SUBIDA,
//        4ª SUBIDA,
//        5ª SUBIDA,
//        6ª SUBIDA,
//        1ª VILA,
//        2ª VILA,
//        3ª VILA,
//        4ª VILA,
//        5ª VILA,
//        1ª RUA,
//        2ª RUA,
//        3ª RUA,
//        5ª RUA,
//        4ª RUA,
//        6ª RUA,
//        7ª RUA,
//        9ª RUA,
//        10ª RUA,
//        11ª RUA,
//        12ª RUA,
    ESTACIONAMENTO,
    VALA,
    RUA_DE_PEDESTRE,
    TÚNEL,
    RODO_ANEL,
    TRAVESSA_PARTICULAR,
    CALÇADA,
    VIA_DE_ACESSO,
    ENTRADA_PARTICULAR,
    ACAMPAMENTO,
    VIA_EXPRESSA,
    ESTRADA_MUNICIPAL,
    AVENIDA_CONTORNO,
    ENTREQUADRA,
    RUA_DE_LIGAÇÃO,
    ÁREA_ESPECIAL,
//    1ª AVENIDA,
//    2ª AVENIDA,
//    3ª AVENIDA,
//    4ª AVENIDA,
//    5ª AVENIDA,
//    6ª AVENIDA,
    PARQUE_MUNICIPAL,
    CONJUNTO_MUTIRÃO,
    PARQUE_RESIDENCIAL,
    VIA_LOCAL,
    RUA_PARTICULAR,
    ESTRADA_VELHA,
    RUA_VELHA,
    TRAVESSA_VELHA,
    ANTIGA_ESTRADA,
    ESTRADA_DE_LIGAÇÃO,
    ESTRADA_ESTADUAL,
    AVENIDA_MARGINAL,
    AVENIDA_VELHA,
    ESTRADA_PARTICULAR,
    VIA_LITORANEA,
}
