package com.webserviceapac.WebServiceApac.Models;

public enum EnumSiglaOrgaoProfissional {
    CONSELHO_DIGITAL_ENFERMAGEM,
    CONSELHO_REGIONAL_DE_ASSISTENCIA_SOCIAL,
    CONSELHO_REGIONAL_DE_BIOLOGIA,
    CONSELHO_REGIONAL_DE_BIOMEDICINA,
    CONSELHO_REGIONAL_DE_EDUCACAO_FISICA,
    CONSELHO_REGIONAL_DE_FARMACIA,
    CONSELHO_REGIONAL_DE_FONOAUDIOLOGIA,
    CONSELHO_REGIONAL_DE_FISIOTERAPIA_E_TERAPIA_OCUPACIONAL,
    CONSELHO_REGIONAL_DE_MEDICINA,
    CONSELHO_REGIONAL_DE_MEDICINA_VETERINARA,
    CONSELHO_REGIONAL_DE_NUTRICAO,
    CONSELHO_REGIONAL_DE_ODONTOLOGIA,
    CONSELHO_REGIONAL_DE_PSICOLOGIA,
    CONSELHO_REGIONAL_DE_TECNICOS_DE_RADIOLOGIA,
    REGISTRO_NO_MINISTERIO_DA_SAUDE_PROGRAMA_MAIS_MEDICOS










}

