package com.webserviceapac.WebServiceApac.Models;

public enum EnumTipoEstadioUICC {
    CARCINOMA_IN_SITU_TISNOMO,
    INSAVAO_LOCAL_INICIAL,
    TUMOR_PRIMARIO_LIMITADO_OU_INVASAO_LINFATICA_REGIONAL_MINIMA,
    TUMOR_LOCAL_EXTENSO_OU_INVASAO_LINFATICA_REGIONAL_EXTENSA,
    TUMOR_LOCALMENTE_AVANCADO_OU_PRESENCA_DE_METASTASE,




}
